# GitHub Funding Configuration for Orion Player
# Creator: Abhinav Santhosh (@abhinavsanthoshpp)

github: [abhinavsanthoshpp]
buy_me_a_coffee: abhinavsanthoshpp
custom: ["https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=upi%3A%2F%2Fpay%3Fpa%3Dabhinava6525%40naviaxis%26pn%3DAbhinav%26cu%3DINR"]
